
package controller;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author hlmth
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenuUI
     */
    public AdminMenu() {
        initComponents();
        setIconInButton();
    }

    public void setIconInButton(){


        ThongKeButton.setIcon(new ImageIcon(getClass().getResource("/images/thongke-ic.png")));

        CaculateBillButton.setIcon(new ImageIcon(getClass().getResource("/images/caculator-ic.png")));

        CustomerDetailButton.setIcon(new ImageIcon(getClass().getResource("/images/customer-ic.png")));

        DepositDetailButton.setIcon(new ImageIcon(getClass().getResource("/images/deposit-ic.png")));

        LogoutButton.setIcon(new ImageIcon(getClass().getResource("/images/logout-ic.png")));
 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ThongKeButton = new javax.swing.JButton();
        CaculateBillButton = new javax.swing.JButton();
        CustomerDetailButton = new javax.swing.JButton();
        TaxButton = new javax.swing.JButton();
        DepositDetailButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NewCustomerButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        ThongKeButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ThongKeButton.setText("Thống kê");
        ThongKeButton.setPreferredSize(new java.awt.Dimension(100, 100));
        ThongKeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongKeButtonActionPerformed(evt);
            }
        });

        CaculateBillButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CaculateBillButton.setText("Caculate Bill");
        CaculateBillButton.setPreferredSize(new java.awt.Dimension(100, 100));
        CaculateBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaculateBillButtonActionPerformed(evt);
            }
        });

        CustomerDetailButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CustomerDetailButton.setText("Customer Detail");
        CustomerDetailButton.setPreferredSize(new java.awt.Dimension(100, 100));
        CustomerDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerDetailButtonActionPerformed(evt);
            }
        });

        TaxButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TaxButton.setText("Tax");
        TaxButton.setPreferredSize(new java.awt.Dimension(100, 100));
        TaxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaxButtonActionPerformed(evt);
            }
        });

        DepositDetailButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DepositDetailButton.setText("Deposit Detail");
        DepositDetailButton.setPreferredSize(new java.awt.Dimension(100, 100));
        DepositDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositDetailButtonActionPerformed(evt);
            }
        });

        LogoutButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.setPreferredSize(new java.awt.Dimension(100, 100));
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("DANH MỤC ADMIN");

        NewCustomerButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        NewCustomerButton1.setText("Thêm Khách Hàng");
        NewCustomerButton1.setPreferredSize(new java.awt.Dimension(100, 100));
        NewCustomerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCustomerButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewCustomerButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(312, 312, 312)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(DepositDetailButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CaculateBillButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TaxButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LogoutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CustomerDetailButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ThongKeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(ThongKeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(CustomerDetailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DepositDetailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(CaculateBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TaxButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(NewCustomerButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ThongKeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThongKeButtonActionPerformed
        jPanel3.removeAll();
        ThongKeAdmin thongKeAdmin = new ThongKeAdmin();
        jPanel3.add(thongKeAdmin.getContentPane());
        jPanel3.revalidate();
        jPanel3.repaint();
    }//GEN-LAST:event_ThongKeButtonActionPerformed

    private void CaculateBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaculateBillButtonActionPerformed
        jPanel3.removeAll();
        CaculatorBill caculatorb = new CaculatorBill(); 
        jPanel3.add(caculatorb.getContentPane());
        jPanel3.revalidate();
        jPanel3.repaint();
    }//GEN-LAST:event_CaculateBillButtonActionPerformed

    private void CustomerDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerDetailButtonActionPerformed
        jPanel3.removeAll();
        CustomerDetail customerDetail = new CustomerDetail(); 
        jPanel3.add(customerDetail.getContentPane());
        jPanel3.revalidate();
        jPanel3.repaint();
    }//GEN-LAST:event_CustomerDetailButtonActionPerformed

    private void TaxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaxButtonActionPerformed
        jPanel3.removeAll();
        TaxUpdate unity = new TaxUpdate(); 
        jPanel3.add(unity.getContentPane());
        jPanel3.revalidate();
        jPanel3.repaint();
    }//GEN-LAST:event_TaxButtonActionPerformed

    private void DepositDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositDetailButtonActionPerformed
        jPanel3.removeAll();
        DepositDetail depositdetail = new DepositDetail(); 
        jPanel3.add(depositdetail.getContentPane());
        jPanel3.revalidate();
        jPanel3.repaint();
    }//GEN-LAST:event_DepositDetailButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        setVisible(false);
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void NewCustomerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCustomerButton1ActionPerformed
        jPanel3.removeAll();
        NewCustomer newCustomer = new NewCustomer(); 
        jPanel3.add(newCustomer.getContentPane());
        jPanel3.revalidate();
        jPanel3.repaint();
    }//GEN-LAST:event_NewCustomerButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminMenu adminMenu = new AdminMenu();
                // Set the window to appear in the center of the screen
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                adminMenu.setLocation(dim.width / 2 - adminMenu.getSize().width / 2, dim.height / 2 - adminMenu.getSize().height / 2);
                adminMenu.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CaculateBillButton;
    private javax.swing.JButton CustomerDetailButton;
    private javax.swing.JButton DepositDetailButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton NewCustomerButton1;
    private javax.swing.JButton TaxButton;
    private javax.swing.JButton ThongKeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
